services:
  redis:
    image: redis:latest
    container_name: redis-bullmq
    ports:
      - "2323:6379"

  postgres:
    image: postgres:16
    container_name: postgres-school-ai
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aiuser
      POSTGRES_PASSWORD: aipassword
      POSTGRES_DB: ai_product_db
    volumes:
      - postgres_school_data:/var/lib/postgresql/data

volumes:
  postgres_school_data: